-- Liste de départ (noms génériques, sans photo) : volontairement non exhaustive.
INSERT INTO extended_catalog (category,name,search_text,source) VALUES
  ('legumes','Champignons','champignons','seed-v1'),
  ('legumes','Poireaux','poireaux','seed-v1'),
  ('legumes','Choux-fleurs','choux-fleurs','seed-v1'),
  ('legumes','Brocolis','brocolis','seed-v1'),
  ('legumes','Épinards','epinards','seed-v1'),
  ('legumes','Petits pois','petits pois','seed-v1'),
  ('legumes','Navets','navets','seed-v1'),
  ('legumes','Betteraves','betteraves','seed-v1'),
  ('legumes','Radis','radis','seed-v1'),
  ('legumes','Céleri','celeri','seed-v1'),
  ('legumes','Potiron','potiron','seed-v1'),
  ('legumes','Fenouil','fenouil','seed-v1'),
  ('legumes','Piments','piments','seed-v1'),
  ('legumes','Gingembre','gingembre','seed-v1'),
  ('legumes','Aneth','aneth','seed-v1'),
  ('legumes','Chou','chou','seed-v1'),
  ('legumes','Salade verte','salade verte','seed-v1'),
  ('legumes','Maïs','mais','seed-v1'),
  ('fruits','Pastèque','pasteque','seed-v1'),
  ('fruits','Melon','melon','seed-v1'),
  ('fruits','Pêches','peches','seed-v1'),
  ('fruits','Abricots','abricots','seed-v1'),
  ('fruits','Cerises','cerises','seed-v1'),
  ('fruits','Mangues','mangues','seed-v1'),
  ('fruits','Ananas','ananas','seed-v1'),
  ('fruits','Kiwis','kiwis','seed-v1'),
  ('fruits','Dattes','dattes','seed-v1'),
  ('fruits','Figues','figues','seed-v1'),
  ('fruits','Grenades','grenades','seed-v1'),
  ('fruits','Prunes','prunes','seed-v1'),
  ('laitages','Crème dessert','creme dessert','seed-v1'),
  ('laitages','Fromage blanc','fromage blanc','seed-v1'),
  ('laitages','Mozzarella','mozzarella','seed-v1'),
  ('laitages','Lait concentré','lait concentre','seed-v1'),
  ('laitages','Lait en poudre','lait en poudre','seed-v1'),
  ('laitages','Lben','lben','seed-v1'),
  ('laitages','Fromage frais','fromage frais','seed-v1'),
  ('epicerie','Couscous','couscous','seed-v1'),
  ('epicerie','Maïs en conserve','mais en conserve','seed-v1'),
  ('epicerie','Haricots blancs','haricots blancs','seed-v1'),
  ('epicerie','Harissa','harissa','seed-v1'),
  ('epicerie','Paprika','paprika','seed-v1'),
  ('epicerie','Curcuma','curcuma','seed-v1'),
  ('epicerie','Cannelle','cannelle','seed-v1'),
  ('epicerie','Cacao en poudre','cacao en poudre','seed-v1'),
  ('epicerie','Pâte à tartiner','pate a tartiner','seed-v1'),
  ('epicerie','Biscuits','biscuits','seed-v1'),
  ('epicerie','Céréales','cereales','seed-v1'),
  ('epicerie','Vinaigre','vinaigre','seed-v1'),
  ('epicerie','Moutarde','moutarde','seed-v1'),
  ('epicerie','Mayonnaise','mayonnaise','seed-v1'),
  ('epicerie','Ketchup','ketchup','seed-v1'),
  ('epicerie','Olives','olives','seed-v1'),
  ('epicerie','Amandes','amandes','seed-v1'),
  ('epicerie','Noix','noix','seed-v1'),
  ('epicerie','Levure de boulanger','levure de boulanger','seed-v1'),
  ('epicerie','Sucre glace','sucre glace','seed-v1'),
  ('epicerie','Sucre vanillé','sucre vanille','seed-v1'),
  ('epicerie','Farine complète','farine complete','seed-v1'),
  ('viandes','Agneau','agneau','seed-v1'),
  ('viandes','Dinde','dinde','seed-v1'),
  ('viandes','Merguez','merguez','seed-v1'),
  ('viandes','Sardines en conserve','sardines en conserve','seed-v1'),
  ('viandes','Crevettes','crevettes','seed-v1'),
  ('viandes','Saucisses','saucisses','seed-v1'),
  ('viandes','Jambon de dinde','jambon de dinde','seed-v1'),
  ('surgeles','Légumes surgelés','legumes surgeles','seed-v1'),
  ('surgeles','Glaces','glaces','seed-v1'),
  ('surgeles','Poisson pané','poisson pane','seed-v1'),
  ('surgeles','Pâte feuilletée','pate feuilletee','seed-v1'),
  ('pain','Baguette','baguette','seed-v1'),
  ('pain','Pain complet','pain complet','seed-v1'),
  ('pain','Brioche','brioche','seed-v1'),
  ('pain','Biscottes','biscottes','seed-v1'),
  ('pain','Crêpes','crepes','seed-v1'),
  ('pain','Gâteaux secs','gateaux secs','seed-v1'),
  ('boissons','Boisson gazeuse','boisson gazeuse','seed-v1'),
  ('boissons','Sirop','sirop','seed-v1'),
  ('boissons','Eau gazeuse','eau gazeuse','seed-v1'),
  ('boissons','Café en capsules','cafe en capsules','seed-v1'),
  ('boissons','Tisane','tisane','seed-v1'),
  ('boissons','Lait d’amande','lait d''amande','seed-v1'),
  ('maison','Pastilles lave-vaisselle','pastilles lave-vaisselle','seed-v1'),
  ('maison','Désodorisant','desodorisant','seed-v1'),
  ('maison','Papier aluminium','papier aluminium','seed-v1'),
  ('maison','Film alimentaire','film alimentaire','seed-v1'),
  ('maison','Piles','piles','seed-v1'),
  ('maison','Ampoules','ampoules','seed-v1'),
  ('maison','Sacs congélation','sacs congelation','seed-v1'),
  ('maison','Détartrant','detartrant','seed-v1'),
  ('maison','Dégraissant','degraissant','seed-v1'),
  ('hygiene','Déodorant','deodorant','seed-v1'),
  ('hygiene','Coton','coton','seed-v1'),
  ('hygiene','Rasoirs','rasoirs','seed-v1'),
  ('hygiene','Brosse à dents','brosse a dents','seed-v1'),
  ('hygiene','Après-shampooing','apres-shampooing','seed-v1'),
  ('hygiene','Protections hygiéniques','protections hygieniques','seed-v1'),
  ('hygiene','Couches','couches','seed-v1'),
  ('hygiene','Crème hydratante','creme hydratante','seed-v1'),
  ('hygiene','Sérum physiologique','serum physiologique','seed-v1');
